### ISSUE TITLE
選択した難易度とは異なる難易度の情報を送信している

### ISSUE THREAD

**Issue by tkns3** [denpadokei/HttpStatusExtention#10]
# 問題の内容

複数の難易度がある曲の簡単な難易度を選択すると一番上の難易度の情報を送信している。
例えばExpert+、Expert、HardのうちHardを選択するとExpert+の情報を送信している。

# 問題の実装

`foreach (var diff in chara)`の外でdiffDataをnewしているのでdicにTryAddしたdiffDataの中身がforeachで書き換えらてしまっている。

https://github.com/denpadokei/HttpStatusExtention/blob/1d38a0d468c17a015cefcc5637cbd7449a16b334/HttpStatusExtention/SongDetailsCaches/SongDetailsCacheUtility.cs#L34-L52

**Comment by denpadokei** [comment]
報告ありがとうございます。
まったくもっておっしゃる通りです。すぐ修正します。
